endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true
  prefix: /nts/plcc
  routes:
    customer: 
      path: /customer/**
      serviceId: card-service
      retryable: true
    config:
      path: /config/**
      serviceId: configuration-service
      retryable: true
    transaction:
      path: /trans/**
      serviceId: transaction-service
      retryable: true
    rule:
      path: /rule/**
      serviceId: rule-service
      retryable: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

server:
  port: 8765
  
management:
  security:
    enabled: false 
  
eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 500000

service:
  auth:
    username: PLCC-SERVICE-USER
    password: NkVWV0NXU1IzMFVONzVDSFZWTElZVjhJNkJGUEFSMUs=

            
security:
  basic:
    enabled: true
    
api:
  authentication:
    -
      username: PLCC-INT-SYSTEM
      password: QTJDODY1ODVKUFhUN1hOS1dFT0ROM0hWVVZLR0xKRjI=
      role: INTERNAL_USER 
    -
      username: PLCC-EXT-USER-1001
      password: OExTVjJTTVNaSkgyRDdMNDdWWVFOSVhONFRFSTdVVDg=
      role: EXTERNAL_USER 
    -
      username: PLCC-EXT-USER-1002
      password: MEY0QjZLNU9OTkUxQjM5NDhaTDkxTU9aOVpTNUNRTFk=
      role: EXTERNAL_USER 
