spring:
  application:
    name: billing-service
    
server:
  port: 3333

  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  healthcheck:
    enabled: true